# Generated by Django 2.2 on 2023-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
