# Generated by Django 2.2 on 2023-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20231212_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
