from django.urls import path
from . import views

urlpatterns = [
    path("",views.home, name="home"),
    path("register",views.register, name="register"),
    path("all_reviews/",views.all_reviews, name="all_reviews"),
    path("login",views.signin, name="login"),
    path("review",views.review, name="review"),
    path("loggedin",views.loggedin, name="loggedin"),
    path("logout",views.logout, name="logout"),
    path("technology",views.technology, name="technology"),
    path("entertainment",views.entertainment, name="entertainment"),
    path("medical",views.medical, name="medical"),
    path("company_details",views.company_details, name="company_details"),
    path("index",views.index, name="index"),
    path("index_ent",views.index_ent, name="index_ent"),
    path("index_",views.index_, name="index_"),
    path("index_tech",views.index_tech, name="index_tech"),
    path("index_fashion",views.index_fashion, name="index_fashion"),
    path("index_med",views.index_med, name="index_med"),
    path("index_cos",views.index_cos, name="index_cos"),
    path("index_aut",views.index_aut, name="index_aut"),
    path("index_travel",views.index_travel, name="index_travel"),
    path("index_food",views.index_food, name="index_food"),
    path("index_other",views.index_other, name="index_other"),
    path("index_real_estate",views.index_real_estate, name="index_real_estate"),
    path("index_fianance",views.index_fianance, name="index_fianance"),
    path("index_education",views.index_education, name="index_education"),
    path("fashion",views.fashion, name="fashion"),
    path("cosmetics",views.cosmetics, name="cosmetics"),
    path("automobiles",views.automobiles, name="automobiles"),
    path("real_estate",views.real_estate, name="real_estate"),
    path("travel",views.travel, name="travel"),
    path("fianance",views.fianance, name="fianance"),
    path("food",views.food, name="food"),
    path("education",views.education, name="education"),
    path("other",views.other, name="other"),
]
